[ODPM-212] "Search Count" graph
OpenDataPolicingNC/Traffic-Stops pull request #234
Opened 2018-11-01 19:18 UTC by nmashton

To let users view searches grouped by "type", this adds a new graph-table pair on the model of "Departmental Stop Count" and the API endpoint to support it.

The new API endpoint is a simple addition that slices the year-by-year search counts by type and adds the type to each object as `search__type`. This new endpoint is added to the cache-priming system.

The changes on the front-end are a little hairy because we want to reuse as much as possible from `StopByReasonAndRace` while respecting the differences between the data they consume. It wouldn't be cool to force the "search count" API endpoint to generate data with weird labels (`stops`, `purpose`, etc) for the historical reason that this graph was based on another one that consumed an API where those labels made sense. Hence we need to create generalized versions of the `StopByReasonAndRace` machinery that lets us define what part of the API's return value we're interested in, the name of the group-by key, the human-readable name of the values under discussion, etc.

The former `StopByReasonAndRace` module has been renamed `IncidentByReasonAndRace`, and the changes in that module all relate to changing hard-coded values to references to abstract properties specified on the subclasses. For example, the use of `this.data.raw.stops` is systematically replaced by `this._raw_data()`.

The new API handler, graph, and table are all defined as subclasses from the contents of `IncidentByReasonAndRace` and linked in by the usual means.

2018-11-02 22:00 UTC, copelco requested changes
This runs locally for me but I would like to see the other PR merged first and pulled into this branch before approving.

2018-11-02 22:00 UTC, copelco commented on nc/tests/test_api.py
> +    def test_searches_by_reason(self):
Did the test suite run for you? I got a bunch of error messages, but they all seemed to pass. Maybe it's been like that for a while.

2018-11-02 22:00 UTC, copelco commented on traffic_stops/static/js/app/common/IncidentByReasonAndRace.js
> +export const IRRHandlerBase = DataHandlerBase.extend({
I'm having a little trouble seeing how these change will impact the Stop Count graph in #233. Maybe we can merge it first and update this branch to see?

2018-11-05 15:53 UTC, nmashton commented on nc/tests/test_api.py
> +    def test_searches_by_reason(self):
Ditto, but it doesn't look clearly related to what I'm doing in this branch. Same thing happens on `docker-setup` branch.

2018-11-05 16:23 UTC, copelco commented on nc/tests/test_api.py
> +    def test_searches_by_reason(self):
👍

2018-11-05 16:57 UTC, copelco approved these changes
Whew, my JS chops are rusty, but the refactor looks good to me! :)

Looks good to me :shipit:

2018-11-05 16:57 UTC, copelco commented on traffic_stops/static/js/app/states/nc/SearchByType.js
> +  Stops: Stops,
Nice, these look reasonably DRY now with the refactor!

2018-11-05 17:00 UTC, merged